# Generated by Django 4.2.4 on 2023-08-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255, verbose_name='Model')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('is_appreciated', models.BooleanField(default=False, verbose_name='Is appreciated')),
                ('import_id', models.IntegerField(blank=True, null=True, verbose_name='Import id')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CarYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(null=True, verbose_name='Year from')),
                ('year_to', models.IntegerField(null=True, verbose_name='Year to')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('import_id', models.IntegerField(blank=True, null=True, verbose_name='Import id')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='cars.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Car year',
                'verbose_name_plural': 'Car years',
            },
        ),
    ]
