# Generated by Django 4.2.4 on 2023-08-07 06:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('preview', models.ImageField(upload_to='', verbose_name='Preview')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video link')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Short description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created_at',),
            },
        ),
    ]
