# Generated by Django 4.2.4 on 2023-08-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_path_field', models.CharField(max_length=12, unique=True)),
                ('date_at', models.DateTimeField(verbose_name='Date at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prepayment')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('confirm_work',
                 models.CharField(choices=[('new', 'New'), ('confirm', 'Confirm'), ('refused', 'Refused')],
                                  default='new', max_length=255, verbose_name='Confirm on work')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('car_registration',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='Car registration')),
                ('car_year', models.IntegerField(blank=True, null=True, verbose_name='Car year')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('post_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post code')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                          related_name='order_car', to='cars.car', verbose_name='Car')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='partner_order', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Partner')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='order', to='booking.employee',
                                                  verbose_name='Responsible')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='request.servicevariation', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255, verbose_name='Paypal ref id')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('no_paid', 'Not paid')], default='no_paid',
                                            max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                            to='booking.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='OrderAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                            to='booking.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order attachment',
                'verbose_name_plural': 'Order attachments',
            },
        ),
    ]
