# Generated by Django 4.2.4 on 2023-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('no_paid', 'Not paid'), ('part payment', 'Part payment')], default='no_paid', max_length=255, verbose_name='Status'),
        ),
    ]
