# Generated by Django 4.2.4 on 2023-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('completed', 'Completed'), ('paid', 'Paid')], default='new', max_length=20, null=True),
        ),
    ]
