# Generated by Django 4.2.4 on 2023-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_phone_mechanic', models.BooleanField(default=True, verbose_name='Is phone mechanic')),
                ('timeout', models.IntegerField(default=10, verbose_name='Timeout')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('message2', models.TextField(default='', verbose_name='Message')),
                ('message3', models.TextField(default='', verbose_name='Message')),
                ('to_phone', models.CharField(max_length=255, verbose_name='To phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('log', models.TextField(verbose_name='Log')),
                ('template', models.CharField(choices=[('request', 'After request'), ('order_payed', 'After order payed')], max_length=255, verbose_name='Template')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
            ],
            options={
                'verbose_name': 'Sms message',
                'verbose_name_plural': 'Sms messages',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('request', 'After request'), ('order_payed', 'After order payed')], max_length=255, verbose_name='Template')),
                ('message', models.TextField(verbose_name='Message 1')),
                ('message2', models.TextField(default='', verbose_name='Message 2')),
                ('message3', models.TextField(default='', verbose_name='Message 3')),
            ],
            options={
                'verbose_name': 'Sms template',
                'verbose_name_plural': 'Sms templates',
            },
        ),
    ]
