# Generated by Django 4.2.4 on 2023-08-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='message2',
            field=models.TextField(blank=True, default='', verbose_name='Message 2'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message3',
            field=models.TextField(blank=True, default='', verbose_name='Message 3'),
        ),
    ]
