# Generated by Django 4.2.4 on 2023-08-12 19:03

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Banner image')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('bottom_image', models.ImageField(null=True, upload_to='', verbose_name='Bottom image')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Review rating')),
                ('reviews_amount', models.PositiveIntegerField(default=0, verbose_name='Reviews amount')),
                ('reviews_link', models.CharField(default='/', max_length=255, verbose_name='Review link')),
            ],
            options={
                'verbose_name': 'Main page',
                'verbose_name_plural': 'Main page',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('review', ckeditor.fields.RichTextField(verbose_name='Review')),
                ('stars', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Stars amount')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
                ('author', models.CharField(default='', max_length=255, verbose_name='Author')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Typical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Typical',
                'verbose_name_plural': 'Typical',
            },
        ),
        migrations.CreateModel(
            name='MainPageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.mainpage')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
