# Generated by Django 4.2.4 on 2023-08-12 19:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('variation', models.CharField(choices=[('static_distance', 'Static plus distance'), ('car_distance', 'Car price plus distance'), ('static', 'Static'), ('else', 'Something else')], max_length=255, verbose_name='Variation')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('ordering', models.IntegerField(blank=True, default=0, verbose_name='Ordering')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('title_style', ckeditor.fields.RichTextField(null=True, verbose_name='Title styled')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('is_display', models.BooleanField(default=True, verbose_name='Is displaying on main page')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Service variation',
                'verbose_name_plural': 'Service variations',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration', models.CharField(max_length=255, verbose_name='Car registration')),
                ('car_year', models.IntegerField(blank=True, null=True, verbose_name='Car year')),
                ('post_code', models.CharField(max_length=255, verbose_name='Post code')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Full name')),
                ('contacts', models.CharField(max_length=255, null=True, verbose_name='Contacts')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('is_work', 'In work'), ('done', 'Done')], default='pending', max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_car', to='cars.car')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.servicevariation', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration', models.CharField(max_length=255, verbose_name='Car registration')),
                ('post_code', models.CharField(max_length=255, verbose_name='Post code')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('car_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request', verbose_name='Requests')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.servicevariation', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
